name: decagon_weather
description: Weather App

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #location
  geolocator: ^9.0.2
  geocoding: ^2.0.5

  intl: ^0.18.0

  #stored data
  shared_preferences: ^2.0.15
  injectable: ^2.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  provider: ^6.0.5
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.5
  package_info_plus: ^3.0.2
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:  
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

