 name: Flutter workflow
 
 on:
   pull_request:
   push:
     branches:
       - dev
 
 jobs:
   qa:
     name: Quality Assurance
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        name: Install Dependencies
      - run: flutter pub get
        name: Format all file in the lib directory
      - run: flutter format lib
        name: Analyze Code, searching for problems and errors
      - run: flutter analyze --no-pub
        # Uncomment when build_runner is added to the project
        #   name: Generate necessary files and delete conflicting files
        # - run: flutter packages pub run build_runner build --delete-conflicting-outputs
        #   name: Track changes made on a file
        # - run: git diff --exit-code
       - name: Running tests without coverage
         run: flutter test --no-pub
