 name: Flutter workflow
 
 on:
   pull_request:
   push:
     branches:
       - dev
 
 jobs:
   qa:
     name: Quality Assurance
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: subosito/flutter-action@v2
       - name: Install dependencies
         run: flutter pub get
       - name: Running the formatter
         run: flutter format lib/
       - name: Running the analyzer
         run: flutter analyze --no-pub
#        - name: Running code generation
#          run: flutter pub run build_runner build --delete-conflicting-outputs
#        - name: Verifying different changes has not been made
#          run: git diff --exit-code
       - name: Running tests without coverage
         run: flutter test --no-pub
